### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Vinicius-Soares** [elloa/pca-coinlabel#14]
README.md do Repositório:
Dúvida sobre a maneira de rotular a moeda de 1 real

A professora Elloa ensinou a rotular a moeda de 1 real como "1", porém o tutorial ensina a rotular como "100", qual é a maneira correta para esse caso?

**Comment by yonekura-dc** [comment]
Rotula como 100.

**Comment by Vinicius-Soares** [comment]
Ok
