### ISSUE TITLE
1915310028/10_1477289640.jpg

### ISSUE THREAD

**Issue by EdOliv** [elloa/pca-coinlabel#37]
Dedo cobrindo parcialmente uma moeda, mas é possível identificá-la.

**Comment by yonekura-dc** [comment]
Segmenta a moeda normalmente (como um círculo) e segmenta cada dedo usando polígonos.

![finger_over](https://user-images.githubusercontent.com/34317256/68777876-b8e8f000-0608-11ea-8f73-4f140cf9f27b.png)
