### ISSUE TITLE
1915310030/75_1477850484.jpg

### ISSUE THREAD

**Issue by aliciamilani** [elloa/pca-coinlabel#51]
**Descrição**
O que fazer em casos onde uma mão está presente na foto?

Matricula: 1915310030
foto: 75_1477850484.jpg

![75_1477850484](https://user-images.githubusercontent.com/38166881/68825845-0c435880-0672-11ea-889a-93007892ea25.jpg)

**Comment by yonekura-dc** [comment]
Pode pular essa.
